#!/usr/bin/env bash
# build_installer.sh, the generator.
#
# The delivered file is one file because a phone has no clone and run
# workflow anybody uses twice. It is not written by hand, because it
# carries three other installers inside it and a hand copy of a payload
# is a second copy of that payload, which drifts.
#
#   tools/build_installer.sh          write N-maha_commute_vN.sh
#   tools/build_installer.sh --check  build to a temp file and compare,
#                                     exit 1 if the committed artefact
#                                     is stale. This is a gate check.
#
# Everything it writes is derived: the version appears at both ends of
# the filename because one number produced both, and the payload
# checksums in the header are computed here rather than typed.

set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)

# The filename rule lives in one place, src/05_lib.sh, and the build
# calls it rather than repeating it. Two implementations of one naming
# rule is how the two ends of a name come to disagree.
. src/05_lib.sh
. src/naming.sh
VERSION=$(tr -d ' \n' < VERSION)
OUT=$(maha_artefact_name "$VERSION")
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# id : source file : version : command : appdir : port : one line
APPS="day:13-install-day-commute-termux-v13.sh:v13:day.commute:.commute:8082:the daytime ride
night:9-night_commute_v9.sh:v9:night.commute:.nightcommute:8087:the four night trams
all:39-install-all_commute-termux-v39.sh:v39:all.commute:.all.commute:8084:every station around you"

SALT="7c1a"
NL=$'\n'
OLDIFS="$IFS"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
BUILD="$TMP/out.sh"

fail() { printf 'build: %s\n' "$1" >&2; exit 1; }

# ---- guards before a single byte is written -------------------
IFS="$NL"
for line in $APPS; do
  id=$(printf '%s' "$line" | cut -d: -f1)
  src="src/payloads/$(printf '%s' "$line" | cut -d: -f2)"
  [ -f "$src" ] || fail "missing payload $src"
  # A payload carrying a line equal to its own heredoc terminator would
  # end the heredoc early and take the rest of the file with it.
  delim="MAHA_PAY_${id}_${SALT}"
  if grep -qx "$delim" "$src"; then fail "$src contains the delimiter $delim"; fi
  # A key that survived the strip must never reach the artefact.
  if grep -qE 'AIza[A-Za-z0-9_-]{30,}' "$src"; then fail "$src still carries a key shape"; fi
done
IFS="$OLDIFS"
for f in src/00_head.sh src/05_lib.sh src/20_menu.sh src/30_install_one.sh src/40_main.sh; do
  [ -f "$f" ] || fail "missing $f"
done
for d in MAHA_MENU_${SALT} MAHA_INSTALLONE_${SALT}; do
  grep -qx "$d" src/20_menu.sh src/30_install_one.sh && fail "delimiter $d appears in a source"
done

# ---- the provenance header ------------------------------------
hdr="$TMP/hdr.txt"
{
  printf '# %s   MAHA COMMUTE %s\n' "$OUT" "v$VERSION"
  printf '#\n'
  printf '# Generated by tools/build_installer.sh. Do not edit this file by\n'
  printf '# hand: it is assembled from src/ and every hand edit is lost on\n'
  printf '# the next build. The sources are the ones to change.\n'
  printf '#\n'
  printf '# built            %s\n' "$(date -u '+%Y-%m-%d %H:%M UTC')"
  printf '# payloads, as carried, key stripped:\n'
  IFS="$NL"
for line in $APPS; do
    id=$(printf '%s' "$line" | cut -d: -f1)
    src="src/payloads/$(printf '%s' "$line" | cut -d: -f2)"
    ver=$(printf '%s' "$line" | cut -d: -f3)
    printf '#   %-6s %-4s %8s bytes  sha256 %s\n' \
      "$id" "$ver" "$(wc -c < "$src" | tr -d ' ')" \
      "$(sha256sum "$src" | cut -c1-16)"
  done
  IFS="$OLDIFS"
  printf '#\n'
  printf '# The Google Maps key that was inside two of these payloads has\n'
  printf '# been taken out and replaced with a placeholder. The installer\n'
  printf '# finds a key on the phone, or asks, and puts it back at install\n'
  printf '# time into a copy that is deleted straight afterwards.\n'
} > "$hdr"

# ---- assemble --------------------------------------------------
verd=$(printf '%s\n' "$APPS" | grep '^day:'   | cut -d: -f3)
vern=$(printf '%s\n' "$APPS" | grep '^night:' | cut -d: -f3)
vera=$(printf '%s\n' "$APPS" | grep '^all:'   | cut -d: -f3)

python3 - "$ROOT" "$hdr" "$BUILD" "$OUT" "$verd" "$vern" "$vera" <<'PY'
import sys, pathlib
root, hdr, build, outname, vd, vn, va = sys.argv[1:8]
root = pathlib.Path(root)
head = (root / "src/00_head.sh").read_text()
head = head.replace("# @@HEADER@@", pathlib.Path(hdr).read_text().rstrip())
head = head.replace("@@FILENAME@@", outname)
head = head.replace("@@VER_DAY@@", vd).replace("@@VER_NIGHT@@", vn).replace("@@VER_ALL@@", va)
pathlib.Path(build).write_text(head)
PY

{
  cat src/05_lib.sh
  printf '\n# ---------------------------------------------------------------\n'
  printf '# the three payloads, whole and unchanged apart from the key\n'
  printf '# ---------------------------------------------------------------\n'
  printf 'maha_emit_payload() {\n  case "$1" in\n'
  IFS="$NL"
for line in $APPS; do
    id=$(printf '%s' "$line" | cut -d: -f1)
    src="src/payloads/$(printf '%s' "$line" | cut -d: -f2)"
    delim="MAHA_PAY_${id}_${SALT}"
    printf "    %s) cat <<'%s'\n" "$id" "$delim"
    cat "$src"
    printf '%s\n      ;;\n' "$delim"
  done
  IFS="$OLDIFS"
  printf '  esac\n}\n\n'

  printf 'maha_emit_menu() {\n  cat <<%s\n' "'MAHA_MENU_${SALT}'"
  cat src/20_menu.sh
  printf 'MAHA_MENU_%s\n}\n\n' "$SALT"

  printf 'maha_emit_install_one() {\n  cat <<%s\n' "'MAHA_INSTALLONE_${SALT}'"
  cat src/30_install_one.sh
  printf 'MAHA_INSTALLONE_%s\n}\n\n' "$SALT"

  cat src/40_main.sh
} >> "$BUILD"

# The last line exists only when the whole file arrived. bash -n cannot
# answer that question: a file cut in half mid heredoc parses, warns on
# stderr and exits zero.
printf '\n# MAHA_COMMUTE_SENTINEL v%s %s\n' "$VERSION" \
  "$(grep -v '^# built ' "$BUILD" | sha256sum | cut -c1-16)" >> "$BUILD"

# ---- the build checks its own output ---------------------------
nout=$(bash -n "$BUILD" 2>&1 || true)
[ -z "$nout" ] || fail "the generated file does not parse cleanly: $nout"
grep -qE 'AIza[A-Za-z0-9_-]{30,}' "$BUILD" && fail "a key shape reached the artefact"
tail -1 "$BUILD" | grep -q '^# MAHA_COMMUTE_SENTINEL' || fail "no sentinel"

if [ "$CHECK" = "1" ]; then
  if [ ! -f "$OUT" ]; then
    printf 'stale: %s has never been built\n' "$OUT"; exit 1
  fi
  # The build stamp differs every run, so compare everything else.
  if diff <(grep -v '^# built ' "$OUT") <(grep -v '^# built ' "$BUILD") >/dev/null; then
    printf 'fresh: %s matches src/\n' "$OUT"; exit 0
  fi
  printf 'stale: %s does not match src/, rebuild it\n' "$OUT"; exit 1
fi

cp "$BUILD" "$OUT"
chmod +x "$OUT"
printf 'built %s  %s bytes  sha256 %s\n' \
  "$OUT" "$(wc -c < "$OUT" | tr -d ' ')" "$(sha256sum "$OUT" | cut -c1-16)"
